### ISSUE TITLE
[1.16.5] Latest version(1.0.23) breaks compatibility with Industrial Revolution

### ISSUE THREAD

**Issue by WolfBV** [cybercat-mods/HWG#36]
Latest.log:
[latest.log](https://github.com/AzureDoom/HWG/files/7402301/latest.log)
 
Crash report:
[crash-2021-10-22_22.16.40-client.txt](https://github.com/AzureDoom/HWG/files/7402302/crash-2021-10-22_22.16.40-client.txt)

**Comment by WolfBV** [comment]
Attempting to create a new world results in a crash

**Comment by AzureDoom** [comment]
`Caused by: org.spongepowered.asm.mixin.throwables.MixinError: Encountered undecorated Accessor method in patchouli.mixins.json:AccessorRecipeManager applying to net.minecraft.class_1863` 
Not an issue with HWG, this is an issue with Patchouli that Industrial Revolution is bundling with it's mod. You need to go tell them about this.
